export { default as Home }   from  './Home'
export { default as Login }  from   './Login'
export { default as Purchases }  from   './Purchases'
export { default as Product }  from   './Product'
export { default as Details }  from   './Details'
export { default as PurchasesIdList } from './PurchasesIdList'